### PR TITLE
Add .mp4 as a valid asset extension

### PR DESCRIPTION
**Pull request by appden**

### CODE REVIEW

**Comment by satya164** [comment]
Thank you for the PR

**Comment by appden** [comment]
@satya164 This was merged into `extra-assets` branch, but not `master`. I didn't realize at the time that you had already squash merged `extra-assets` into `master`, or I would have set the target of this PR to be `master`. Sorry about that!

**Comment by joaomilho** [comment]
Although this was added, I get:

```
./src/features/.../dog.mp4
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
@ ./src/features/.../Component.native.js 14:9-36
@ ./src/features/.../index.js
```

Should I report this in an issue?

**Comment by joaomilho** [comment]
Mmm, actually my version didn't have this change, adding the extension by hand fixed.

**Comment by joaomilho** [comment]
Ok so the issue is that this didn't reach any version and the last one published (1.0.0) is from June 2017....

**Pull request merged**
