### PR TITLE
add config path as an option

### PR DESCRIPTION
**Pull request by mathieudutour**
Allow to specify the path to the config file as an option

`haul start --config ./path/to/config.js`

### CODE REVIEW

**Comment by satya164** [comment]
Looks reasonable. Can you check if both absolute and relative paths work?

cc @grabbou

**Comment by mathieudutour** [comment]
oh no good point, only relative path will work with that

**Comment by satya164** [comment]
Okies, should be easy to support both using `path`. Can you do the change?

**Comment by mathieudutour** [comment]
done

**Pull request merged**
